src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Client</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Statute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Statute</label>
        <referenceTo>Statute__c</referenceTo>
        <relationshipLabel>Matters</relationshipLabel>
        <relationshipName>Matters</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Statute__c.object
<CustomObject>
    <label>Statute</label>
    <nameField>
        <label>Statute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statutes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bureau of Labor Statistics</fullName>
                </value>
                <value>
                    <fullName>Employment &amp; Training Administration</fullName>
                </value>
                <value>
                    <fullName>Mine Safety and Health Administration</fullName>
                </value>
                <value>
                    <fullName>Occupational Safety &amp; Health Admin.</fullName>
                </value>
                <value>
                    <fullName>Office of Asst. Secy. for Admin. &amp; Mgt.</fullName>
                </value>
                <value>
                    <fullName>Office of the Deputy Secretary</fullName>
                </value>
                <value>
                    <fullName>Office of the Inspector General</fullName>
                </value>
                <value>
                    <fullName>Solicitor of Labor</fullName>
                </value>
                <value>
                    <fullName>Wage and Hour Division</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Time Allocations</relationshipLabel>
        <relationshipName>Time_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_a_working_day__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is a working day ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Matter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matter</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Time Allocations</relationshipLabel>
        <relationshipName>Time_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Timesheet_project__c</referenceTo>
        <relationshipLabel>Time Allocations</relationshipLabel>
        <relationshipName>Time_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Statute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Statute</label>
        <referenceTo>Statute__c</referenceTo>
        <relationshipLabel>Time Allocations</relationshipLabel>
        <relationshipName>Time_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tasks__c</fullName>
        <label>Tasks</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Legal Services</fullName>
                </value>
                <value>
                    <fullName>Non-Legal Services</fullName>
                </value>
                <value>
                    <fullName>Training Program Related – Giving</fullName>
                </value>
                <value>
                    <fullName>Training Program Related – Participating</fullName>
                </value>
                <value>
                    <fullName>General Administration</fullName>
                </value>
                <value>
                    <fullName>Professional Development</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time Allocation</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Timesheet_project__c.object
<CustomObject>
    <label>Timesheet project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheet projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Client.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Bureau of Labor Statistics</fullName>
    </customValue>
    <customValue>
        <fullName>Employment &amp; Training Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Mine Safety and Health Administration</fullName>
    </customValue>
    <customValue>
        <fullName>Occupational Safety &amp; Health Admin.</fullName>
    </customValue>
    <customValue>
        <fullName>Office of Asst. Secy. for Admin. &amp; Mgt.</fullName>
    </customValue>
    <customValue>
        <fullName>Office of the Deputy Secretary</fullName>
    </customValue>
    <customValue>
        <fullName>Office of the Inspector General</fullName>
    </customValue>
    <customValue>
        <fullName>Solicitor of Labor</fullName>
    </customValue>
    <customValue>
        <fullName>Wage and Hour Division</fullName>
    </customValue>
    <masterLabel>Client</masterLabel>
</GlobalValueSet>

src/classes/PDETimeSheetCtrl.cls
//  Copyright (c) 2023, salesforce.com, inc.
//  All rights reserved.
//  SPDX-License-Identifier: BSD-3-Clause
//  For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

public class PDETimeSheetCtrl {
   /*
    @AuraEnabled
    public static List<AccountProject__c> getProjects(String parentId){
        return [Select Id, Name, Start_Date__c, Stop_Date__c, Project_manager__c, ProgressF__c,
                Next_step__c, Issue__c, Issue_message__c
                from AccountProject__c where Account__c = :parentId];
    }
    */
    
    
    @AuraEnabled
    public static String getProjectName(Id projectId){
      Timesheet_project__c[] Projects = [SELECT Id, Name FROM Timesheet_project__c
                          WHERE Id = :projectId];
      return Projects[0].Name;
    }
    
    @AuraEnabled
    public static Case getCase(Id caseid){
        return [select id,casenumber,Subject,Account.Name,Statute__r.Name,Client__c from case where id =:caseid];
    }
    
    @AuraEnabled
    public static Statute__c getStatute(Id sid){
        return [select id,name from Statute__c  where id =:sid ];
    }
    
    @AuraEnabled
    public static Boolean duplicatemonth(Integer month){
        
        system.debug('*****'+month);
        
        try{
            List<Time_Allocation__c> allnewallocations = new List<Time_Allocation__c>(); 
            
            for(Time_Allocation__c ta : [select Id,Date__c, Is_a_working_day__c, Quantity__c,
                                         Project__c,
                                         Client__c,Contact__c ,Matter__c, Statute__c, Tasks__c
                                         from Time_Allocation__c where CALENDAR_MONTH(Date__c) = :month
                                        ])
            { 
                    
                Time_Allocation__c newta = ta.clone(false,true,true,false);
                newta.Date__c = newta.Date__c.addMonths(1);
                allnewallocations.add(newta);  
            }
            
            if(allnewallocations.size() > 0)
            	insert allnewallocations;                           
            return true;
        }catch(Exception ex){ 
            return false;
        }
        
    }
    
    @AuraEnabled
    public static List<Project_Allocations> getAllocations(String contactId, String startDateStr, String endDateStr){
        Date startDate = Date.valueOf(startDateStr);
        Date endDate = Date.valueOf(endDateStr);
        Time_Allocation__c[] allAllocations = [SELECT Id, Date__c, Is_a_working_day__c, Quantity__c,
                                                          Project__r.Id, Project__r.Name,
                                               			  Client__c,Contact__c ,Matter__c, Statute__c, Tasks__c,
                                               			  Matter__r.CaseNumber,Matter__r.Subject,Matter__r.Client__c,
                                               			  Matter__r.Statute__r.Name,Statute__r.Name
                                                   FROM Time_Allocation__c
                                                   WHERE Date__c >= :startDate AND Date__c <= :endDate
                                                         AND Contact__r.Id = :contactId ];
        //Get DISTINCT UNIQUE PROJECT IDs
        Set<Id> setProjectIds = new Set<Id>();
        for (Integer i = 0; i< allAllocations.size(); i++)
        {
            setProjectIds.add(allAllocations[i].Project__r.Id); // contains distict accounts
        }
        
        //For each project ID, associate all Time_Allocation__c reccords
        Project_Allocations[] allocationsByProject = new list<Project_Allocations>();
        for (Id projectId : setProjectIds) {
    		Time_Allocation__c[] allocations = new List<Time_Allocation__c>();
            for (Time_Allocation__c TA : allAllocations){
                if (TA.Project__r.Id == projectId){
                   allocations.add(TA); 
                }   
            }
            Project_Allocations PA = new Project_Allocations(projectId,allocations[0].Project__r.Name,allocations);
            allocationsByProject.add(PA);    
            
		}
        
        
        return allocationsByProject; 
    }
    
    @AuraEnabled
    public static Integer saveAllocations(Time_Allocation__c[] toUpsert, Time_Allocation__c[] toDelete){
        //upsert toUpsert;
        delete toDelete;
        
        String listType = 'List<Time_Allocation__c>'; 
        List<Time_Allocation__c> castRecords = (List<SObject>)Type.forName(listType).newInstance();
        Integer numberDays = date.daysInMonth(2019, 6);

        List<Time_Allocation__c> allnewallocations = new List<Time_Allocation__c>();
        
        
        castRecords.addAll(toUpsert);
        
        for(Time_Allocation__c ta : castRecords){ 
            
            Date curr = ta.Date__c.addDays(7);
            Integer currmonth = ta.Date__c.month();
            system.debug('********curr'+curr);
            for(; curr.day() <= numberDays && curr.month() == currmonth; curr = curr.addDays(7)){
                
               	Time_Allocation__c newta = ta.clone(false,true,true,false);
                newta.Date__c = curr;
                allnewallocations.add(newta);
            }
            
        }
        upsert castRecords;
        insert allnewallocations;
        system.debug('****\nallnewallocations :'+allnewallocations);
        
        return 1;
    }
    
    public class Project_Allocations{
        @AuraEnabled 
        public ID projectId;
        @AuraEnabled 
        public String projectName;
        @AuraEnabled 
        public List<Time_Allocation__c> allocations;
        Project_Allocations(ID projectId, String projectName, List<Time_Allocation__c> allocations ){
            this.projectId = projectId; this.projectName = projectName; this.allocations=allocations;
        }
        
        
    }
}